#!/usr/bin/env python3
"""
progress.py — hitung progress terjemahan secara otomatis dan tulis ke
Obsidian-Vault/progress/Current-Status.md (blok di antara penanda
`<!-- progress:start -->` dan `<!-- progress:end -->`).

    python tools/progress.py            # cetak saja
    python tools/progress.py --write    # perbarui blok di Current-Status.md
    python tools/progress.py --check    # exit 1 kalau blok tidak sesuai data (CI)

Angka dihitung dari file yang ter-track di git saja (unique_strings.jsonl,
locale/*.jsonl, strings.jsonl), jadi hasilnya sama di mesin mana pun dan
--check bisa dipakai di CI. Dump lain yang ada secara lokal (strings_diff.jsonl,
strings_small*.jsonl) hanya dicetak ke konsol, tidak ditulis ke blok.

Fase baru (Update-N setelah update game) harus ditambahkan ke PHASES di bawah.
"""
import argparse, glob, json, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "tools"))
from expand_locale import load_translated_map

STATUS_PATH = os.path.join(ROOT, "Obsidian-Vault", "progress", "Current-Status.md")
START = "<!-- progress:start — generated by tools/progress.py, do not edit by hand -->"
END = "<!-- progress:end -->"

# (label, file di locale/, idx awal, idx akhir inklusif). Update-N = string dari
# update game (lihat Phase-Roadmap), dihitung terpisah dari korpus asli.
PHASES = [("0", "phase0.jsonl", 0, 799),
          ("1", "phase1.jsonl", 800, 1999),
          ("2", "phase2.jsonl", 2000, 4999),
          ("3", "phase3.jsonl", 5000, 9999),
          ("4", "phase4.jsonl", 10000, 19999),
          ("5", "phase5.jsonl", 20000, 49999),
          ("6", "phase6.jsonl", 50000, 99999)]
PHASES += [(str(n), "phase%d.jsonl" % n, 100000 + (n - 7) * 30000, 129999 + (n - 7) * 30000)
           for n in range(7, 17)]
PHASES += [("17", "phase17.jsonl", 400000, 429886),
           ("Update-1", "update1.jsonl", 429887, 461703)]

# Dump yang ter-track -> dipakai untuk blok. Sisanya hanya info konsol.
TRACKED_DUMPS = [("translate_words_map_en", "strings.jsonl")]
LOCAL_DUMPS = [("translate_words_map_en_diff", "strings_diff.jsonl"),
               ("translate_words_map_en__small", "strings_small.jsonl"),
               ("translate_words_map_en__small_diff", "strings_small_diff.jsonl")]


def pct(a, b):
    return "%.2f%%" % (100.0 * a / b) if b else "—"


def num(n):
    return "{:,}".format(n)


def phase_rows():
    known = {f for _, f, _, _ in PHASES}
    extra = [os.path.basename(p) for p in glob.glob(os.path.join(ROOT, "locale", "*.jsonl"))
             if os.path.basename(p) not in known]
    if extra:
        sys.exit("file locale tanpa entri di PHASES (tambahkan ke tools/progress.py): %s" % extra)
    rows = []
    for label, fname, lo, hi in PHASES:
        path = os.path.join(ROOT, "locale", fname)
        done, first, last = 0, None, None
        if os.path.exists(path):
            with open(path, encoding="utf-8") as f:
                for line in f:
                    if not line.strip():
                        continue
                    i = json.loads(line)["idx"]
                    if first is None:
                        first = i
                    if i != (last + 1 if last is not None else lo) or i > hi:
                        sys.exit("%s: idx %d tidak berurutan dari %d atau di luar %d–%d "
                                 "(jalankan tools/qa_check.py --locale)" % (fname, i, lo, lo, hi))
                    last, done = i, done + 1
        rows.append((label, lo, hi, hi - lo + 1, done))
    return rows


def dump_coverage(dump, src_to_translated):
    path = os.path.join(ROOT, dump)
    if not os.path.exists(path):
        return None
    total = hit = 0
    with open(path, encoding="utf-8") as f:
        for line in f:
            if not line.strip():
                continue
            d = json.loads(line)
            if d.get("deleted"):
                continue
            total += 1
            hit += d["v"] in src_to_translated
    return hit, total


def build_block():
    rows = phase_rows()
    src_to_translated, _ = load_translated_map()

    orig = [r for r in rows if not r[0].startswith("Update")]
    upd = [r for r in rows if r[0].startswith("Update")]
    all_total, all_done = sum(r[3] for r in rows), sum(r[4] for r in rows)
    o_total, o_done = sum(r[3] for r in orig), sum(r[4] for r in orig)
    u_total, u_done = sum(r[3] for r in upd), sum(r[4] for r in upd)

    out = [START, "",
           "## Overall progress", "",
           "| Measure | Done | Total | % |",
           "| --- | ---: | ---: | ---: |",
           "| **Unique strings translated (all)** | **%s** | **%s** | **%s** |"
           % (num(all_done), num(all_total), pct(all_done, all_total)),
           "| ↳ original corpus (Phases 0–17) | %s | %s | %s |"
           % (num(o_done), num(o_total), pct(o_done, o_total)),
           "| ↳ game-update strings (Update-N) | %s | %s | %s |"
           % (num(u_done), num(u_total), pct(u_done, u_total))]
    for name, dump in TRACKED_DUMPS:
        cov = dump_coverage(dump, src_to_translated)
        if cov:
            out.append("| **In-game text coverage** — `%s` entries (`%s`) | **%s** | **%s** | **%s** |"
                       % (name, dump, num(cov[0]), num(cov[1]), pct(*cov)))
    out += ["",
            "Unique strings = rows of `unique_strings.jsonl` with a translation in "
            "`locale/`. In-game coverage counts every entry of the dumped file whose "
            "text has a translation — higher than the unique share because the "
            "earliest phases hold the most frequent strings.",
            "",
            "## Phase status", "",
            "| Phase | Range | Status | Next idx | Done / total | % |",
            "| --- | --- | --- | --- | ---: | ---: |"]
    for label, lo, hi, total, done in rows:
        status = "done" if done == total else ("**active**" if done else "not started")
        nxt = "—" if done == total else num(lo + done)
        out.append("| %s | %s–%s | %s | %s | %s / %s | %s |"
                   % (label, num(lo), num(hi), status, nxt, num(done), num(total),
                      pct(done, total)))
    out += ["", END]
    return "\n".join(out), src_to_translated


def read_status():
    """Kembalikan (isi dokumen, posisi START, posisi END)."""
    with open(STATUS_PATH, encoding="utf-8", newline="") as f:
        doc = f.read()
    s, e = doc.find(START), doc.find(END)
    if s < 0 or e < s:
        sys.exit("penanda progress tidak ditemukan di %s" % STATUS_PATH)
    return doc, s, e


def is_stale():
    """True kalau blok di Current-Status.md tidak sesuai data saat ini."""
    block, _ = build_block()
    doc, s, e = read_status()
    return doc[s:e + len(END)].replace("\r\n", "\n") != block


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    g = ap.add_mutually_exclusive_group()
    g.add_argument("--write", action="store_true", help="perbarui blok di Current-Status.md")
    g.add_argument("--check", action="store_true", help="exit 1 kalau blok basi")
    a = ap.parse_args()

    block, src_to_translated = build_block()
    doc, s, e = read_status()
    nl = "\r\n" if "\r\n" in doc else "\n"
    current = doc[s:e + len(END)].replace("\r\n", "\n")

    if a.check:
        if current != block:
            print("Current-Status.md: blok progress basi — jalankan "
                  "`python tools/progress.py --write` dan commit hasilnya.")
            return 1
        print("Current-Status.md: blok progress sesuai data.")
        return 0

    if a.write:
        with open(STATUS_PATH, "w", encoding="utf-8", newline="") as f:
            f.write(doc[:s] + block.replace("\n", nl) + doc[e + len(END):])
        print("ditulis:", STATUS_PATH)
    else:
        print(block)

    for name, dump in LOCAL_DUMPS:          # info tambahan, tidak masuk blok
        cov = dump_coverage(dump, src_to_translated)
        if cov:
            print("(lokal) %-36s %s / %s (%s)" % (name, num(cov[0]), num(cov[1]), pct(*cov)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
